#!/usr/bin/env python3
# SPDX-License-Identifier: MIT OR Apache-2.0
"""Regenerate the vendored option descriptions and the slider-hint table.

Usage (on a machine running the target Hyprland):

    hyprctl descriptions -j | python3 meta/gen_sliders.py --vendor
    python3 meta/gen_sliders.py            # re-derive sliders.rs only

`--vendor` reads `hyprctl descriptions -j` from stdin and writes
`meta/hyprland-descriptions.json` (minus the machine-specific `current`
values). Either way the script then writes
`crates/hyprconf-core/src/schema/sliders.rs` from that file.

Slider hints are Hyprland's own `min`/`max` for numeric options. They are UI
hints, not limits: the compositor publishes `0..=20` for `decoration:rounding`
yet accepts larger values, so hyprconf never *validates* against them.
"""

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
VENDORED = ROOT / "meta" / "hyprland-descriptions.json"
OUT = ROOT / "crates" / "hyprconf-core" / "src" / "schema" / "sliders.rs"

# A "max" this large is a sentinel for "unbounded", not a useful slider end.
SANE_MAX = 100_000


def vendor() -> None:
    entries = json.load(sys.stdin)
    for entry in entries:
        entry.pop("current", None)
    entries.sort(key=lambda e: e["name"])
    VENDORED.write_text(json.dumps(entries, indent=1, ensure_ascii=False) + "\n")


def fmt(value: float) -> str:
    text = repr(float(value))
    return text if "." in text or "e" in text else text + ".0"


def generate() -> None:
    entries = json.loads(VENDORED.read_text())
    rows = []
    for entry in entries:
        lo, hi = entry.get("min"), entry.get("max")
        if lo is None or hi is None or hi <= lo or hi > SANE_MAX:
            continue
        rows.append(f'    ("{entry["name"]}", {fmt(lo)}, {fmt(hi)}),')
    OUT.write_text(
        "// SPDX-License-Identifier: MIT OR Apache-2.0\n"
        "//! Slider spans for numeric options, taken from Hyprland's own option\n"
        "//! descriptions (`meta/hyprland-descriptions.json`).\n"
        "//!\n"
        "//! **Generated by `meta/gen_sliders.py` — do not edit by hand.** Paths are\n"
        "//! in the compositor's `.conf` spelling; the schema canonicalises them.\n"
        "\n"
        "/// `(path, min, max)` slider hints, sorted by path.\n"
        "#[rustfmt::skip]\n"
        "pub(super) const SLIDERS: &[(&str, f64, f64)] = &[\n"
        + "\n".join(rows)
        + "\n];\n"
    )
    print(f"wrote {len(rows)} slider hints to {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    if "--vendor" in sys.argv[1:]:
        vendor()
    generate()
